#!/usr/bin/env bash

if [ "$1" = "-r" ]; then
  printf "\033[1;36mUNINSTALLING OF POTAZYUM\033[m\n" && sleep 0.1
  printf "\033[1;33m[!]\033[m The uninstalling requires a sudo authentification !\n\n" && sleep 0.1

  ## Deleting the actual potazyum
  sudo rm -rf /bin/potazyum

  printf '\033[1;32mDone ! ;-)\033[m\n' && sleep 0.2
  printf 'If you did not like something, do not hesitate to report it to me or contribute here: https://github.com/maelsan/Potazyum\n'
  exit
fi

printf "\033[1;36mINSTALLATION OF POTAZYUM\033[m\n" && sleep 0.1
printf "\033[1;33m[!]\033[m The installation requires a sudo authentification !\n\n" && sleep 0.1

printf "\033[1;36mLoading\033[m"
max=10
for i in `seq 2 $max`
do
  printf '\033[1;36m.\033[m' && sleep 0.2
done

## Deleting the actual potazyum
sudo rm -rf /bin/potazyum

## Install || Update
sudo cp ./potazyum /bin/potazyum

printf ' \033[1;32mDone ! ;-)\033[m\n' && sleep 0.2
